### ISSUE TITLE
Is this the complete version?

### ISSUE THREAD

**Issue by ZihaoZheng98** [pengfei-luo/MIMIC#1]

**Comment by pengfei-luo** [comment]
Thanks for your attention to our work.

We have uploaded the cleaned data we used in our model and provided all the codes to reproduce the experiments.

If you have any questions, please let me know.

**Comment by pengfei-luo** [comment]
Thanks for your attention to our work.

We have uploaded the cleaned data we used in our model and provided all the codes to reproduce the experiments.

If you have any questions, please let me know.
